### ISSUE TITLE
Configurable modules

### ISSUE THREAD

**Issue by vladvildanov** [RedisLabs/redis-ee-docker#13]
Right now HTTP request that creates DB contains hardcoded modules, which makes it less flexible and could lead to potential problems if at least one of the modules are not available on given docker image.

**Comment by vladvildanov** [comment]
@chayim Also, I'm thinking about bring some Python instead of Shell for the script that builds HTTP request to create database. Looks like it becomes more complex with conditions around modules, OSS cluster/Proxy and potentially something else and Python looks more suitable then Shell

**Comment by ofekshenawa** [comment]
@vladvildanov, that actually sounds pretty cool! Back when we were working on module automation, we set up a system for creating databases and adding modules. We also made use of Redis Enterprise options and integrated a Swagger API library. You might want to check it out; it could save you some effort - https://github.com/RedisLabs/module-tests

**Comment by vladvildanov** [comment]
@ofekshenawa Yeah, that sounds reasonable, the question is how we want to expose this library?

For now it looks like redis-ee-docker is mostly used as tool in CI rather then a tool for local development, but I agree we should consider redis-ee-docker as both and provide a better interface to create/modify DB.

**Comment by chayim** [comment]
@vladvildanov this is out of scope, at least for now. The RLEC team is on that elsewhere. We should be concerned with validation and support of released, and near-released (edge) versions, given our focus. Recommend closing.
